from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    HRFlowable,
)
from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle,
)


def create_pdf_report(data, filename="meeting_report.pdf"):

    doc = SimpleDocTemplate(
        filename,
        leftMargin=40,
        rightMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()

    section_style = ParagraphStyle(
        "SectionStyle",
        parent=styles["Heading2"],
        fontSize=15,
        spaceBefore=12,
        spaceAfter=8,
    )

    footer_style = ParagraphStyle(
        "FooterStyle",
        parent=styles["Italic"],
        fontSize=9,
    )

    elements = []

    # Title
    elements.append(
        Paragraph(data["title"], styles["Title"])
    )

    elements.append(Spacer(1, 10))

    elements.append(
        HRFlowable(width="100%")
    )

    elements.append(Spacer(1, 15))

    # Summary
    elements.append(
        Paragraph("Summary", section_style)
    )

    elements.append(
        Paragraph(
            str(data["summary"]).replace("\n", "<br/>"),
            styles["BodyText"]
        )
    )

    elements.append(Spacer(1, 15))

    # New Page
    

    sections = [
        ("Meeting Minutes", data["meeting_minutes"]),
        ("Action Items", data["action_items"]),
        ("Key Decisions", data["key_decisions"]),
        ("Open Questions", data["open_questions"]),
    ]

    for heading, content in sections:

        elements.append(
            Paragraph(heading, section_style)
        )

        elements.append(
            Paragraph(
                str(content).replace("\n", "<br/>"),
                styles["BodyText"]
            )
        )

        elements.append(Spacer(1, 12))

    elements.append(Spacer(1, 20))

    elements.append(
        HRFlowable(width="100%")
    )

    elements.append(Spacer(1, 8))

    elements.append(
        Paragraph(
            "Generated by AI Video Assistant",
            footer_style
        )
    )

    doc.build(elements)

    return filename